---
title: "Chapter 15 Notes"
author: "Tammy Lightle"
format: html
editor: visual
---

```{r}
set.seed(2025)

coins <- sample(x = 0:1, size = 1000, replace = TRUE)

unique(coins)
length(coins)
typeof(coins)

sum(coins)
```

```{r}
dice <- sample(1:6, 10000, replace = TRUE)

hist(dice,
     breaks = seq(0.5, 6.5, by = 1),
     col = "darkgreen",
     main = "10,000 Fair Dice Rolls",
     xlab = "Face Value")

```

```{r}
barplot(table(dice),
        main = "Counts by Die Face (table method)",
        col = "darkblue",
        xlab = "Face Value",
        ylab = "Count")
```

```{r}
sum_two <- sample(1:6, 10000, TRUE) + sample(1:6, 10000, TRUE)

hist(sum_two,
     breaks = seq(1.5, 12.5, by = 1),
     main = "Sum of Two Dice (10,000 trials)",
     col = "salmon",
     xlab = "Total Sum")
```

```{r}
barplot(table(sum_two),
        main = "Sum of Two Dice (10,000 trials)",
        col = "darkblue",
        xlab = "Face Value",
        ylab = "Count")
```

```{r}
heights <- rnorm(n = 1000, mean = 64, sd = 2.5)

hist(heights, 
     col = "yellowgreen",
     main = "Simulated Female Heights",
     xlab = "Height (inches)")

mean(heights)
sd(heights)
```

```{r}
tails_100 <- replicate(n = 100, expr = sum(sample(0:1, 5000, TRUE)))

summary(tails_100)

hist(tails_100, col = "gold",
     main = "Distribution of Tails in 5,000 Coin Flips (100 reps)",
     xlab = "Count of Tails")
```

```{r}
set.seed(1234)
x <- rnorm(n = 50, mean = 2, sd = 3)

print(x)
```

```{r}
below_zero <- x < 0
below_zero

count <- sum(below_zero)
count
```

```{r}
values_below_zero <- replicate(
  n = 200,
  expr = sum(rnorm(50, mean = 2, sd = 3) < 0)
)

mean(values_below_zero)
sd(values_below_zero)
quantile(values_below_zero, c(.1, .5, .9))
```

```{r}
mean(values_below_zero >= 15)
```

```{r}
risk_halt <- mean(replicate(200, sum(rnorm(50, 2,3) <0)) >= 15)
risk_halt
```

```{r}
threshold <- 15
max_count <- max(values_below_zero)
breaks_int <- seq(2.5, max_count + 0.5, by = 1)

hist(values_below_zero,
     breaks = breaks_int, 
     col = "grey",
     main = "Distribution of Opponents in 50-Student Surveys (200 reps)",
     xlab = "Count of Values Below Zero")

abline(v = threshold, col = "darkred", lwd = 2, lty = 2)
abline(v = mean(values_below_zero), col = "darkblue", lwd = 2, lty = 1)

legend("topright",
       legend = c("Halt Threshold (15)", "Mean Count"),
       col = c("darkred", "darkblue"),
       lty = c(2, 1),
       lwd = 2,
       bg = "white",
       bty = "o")
```

```{r}
rolls <- sample(1:6, 1000, prob = c(.1, .2, 0.2, .05, 0, 0), replace = TRUE)

round(prop.table(table(rolls)), 3)
```

```{r}
set.seed(8000)
biased <- c(.12, .13, .07, .23, .22, .23)
friend_sum <- sample(1:6, size = 1000, replace = TRUE, prob = biased) +
  sample(1:6, size = 1000, replace = TRUE, prob = biased)

fair_sum <- sample(1:6, 1000, TRUE) + sample(1:6, 1000, TRUE)

ploaded <- prop.table(table(friend_sum))
pfair <- prop.table(table(fair_sum))

face_props <- rbind(Bias = ploaded, Fair = pfair)

barplot(face_props,
        beside = TRUE,
        col = c("tomato", "steelblue"),
        main = "Probabilities (2 Dice, 1000 rolls)",
        xlab = "Added Face Values",
        ylab = "Proportion")

legend("topright",
       legend = c("Loaded", "Fair"),
       fill = c("tomato", "steelblue"),
       bty = "n")
```
